openapi: 3.0.0
/api/file/upload-img
  post:
    tags:
      - Upload
      summary: Subir imagenes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: Object
              properties:
                nombreCarpeta:
                  type: string
                  example: Lapiz
                imgs:
                  type: array
                  itmes:
                    type: object
                    properties:
                      nombre:
                        type: string
                        example: Lapiz b1
                      base64:    
                        type: string
                        example: adafadadad